### ISSUE TITLE
Unable to detect changes

### ISSUE THREAD

**Issue by gaby** [tchupp/actions-detect-directory-changes#18]
@tchupp I'm trying to use your gh action but it seems to be unable to detect any changes even though folders have change. This is my CI file:

```yaml
name: Gosec Security Scan

on:
  push:
    branches:
      - "master"
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1
        with:
          included-paths: "!./.github/**"

  gosec-scan:
    runs-on: ubuntu-latest
    needs: detect-changes
    env:
      GO111MODULE: on
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-changes.outputs.changed) }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.x'
          check-latest: true
          cache: false
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run gosec
        working-directory: ${{ matrix.modules }}
        run: gosec ./...
```

When running the following output shows only changes in `.github/`, I also have changes in the `redis` directory

```console
env:
    INCLUDED_PATHS: !./.github/**
    IF_THESE_PATHS_CHANGE_RETURN_ALL_INCLUDED_PATHS: 
    CHANGED_DIRECTORIES: ./.github/workflows
    ALL_DIRECTORIES: . .github .github/ISSUE_TEMPLATE .github/scripts .github/workflows arangodb azureblob badger bbolt coherence couchbase dynamodb etcd memcache memory memory/internal minio mongodb mssql mysql pebble postgres redis ristretto rueidis s3 scylladb sqlite3
```

This warning also shows for the whole action .yml file:

```
Error when evaluating 'strategy' for job 'gosec-scan'. .github/workflows/gosec.yml (Line: 45, Col: 18): Matrix vector 'modules' does not contain any values
```
